version: "3"
services:
  api:
    container_name: api
    restart: always
    build: .
    env_file: .env
    environment:
      DATABASE_URL: "mongodb://$DB_USER:$DB_PASSWORD@mongodb:27017"
      DATABASE_NAME: $DATABASE_NAME
      APP_PORT: $APP_PORT
      NODE_ENV: $NODE_ENV
      JWT_SECRET_KEY: $JWT_SECRET_KEY
      REDIS_URL: $REDIS_URL
      REDIS_USER: $REDIS_USER
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_DATABASE: $REDIS_DATABASE

    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
